# ExportFunctions.py - Ghidra script to export functions and decompiled code
# @category: Headless

from ghidra.app.decompiler import DecompInterface
from ghidra.util.task import ConsoleTaskMonitor
import os

# Get the current program
program = currentProgram
if program is None:
    print("No program loaded!")
else:
    # Setup paths
    output_dir = r"B:\IA_WORKS\2025-01-17_CPR_Rolemaster_Reverse\outputs"
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
    
    # Export function list
    functions_file = os.path.join(output_dir, "functions_list.txt")
    f = open(functions_file, "w")
    f.write("Function Name\tAddress\tSize\n")
    f.write("-" * 50 + "\n")
    
    # Get all functions
    fm = program.getFunctionManager()
    functions = fm.getFunctions(True)  # True = forward iterator
    
    func_count = 0
    for func in functions:
        name = func.getName()
        entry = func.getEntryPoint()
        body = func.getBody()
        size = body.getNumAddresses()
        
        f.write("%s\t%s\t%d\n" % (name, entry, size))
        func_count += 1
    
    f.write("\nTotal functions: %d\n" % func_count)
    f.close()
    
    print("Exported %d functions to %s" % (func_count, functions_file))
    
    # Setup decompiler
    decompiler = DecompInterface()
    decompiler.openProgram(program)
    
    # Export decompiled code
    decompiled_file = os.path.join(output_dir, "decompiled_code.c")
    f = open(decompiled_file, "w")
    f.write("// Decompiled code from CPR093.exe\n")
    f.write("// Generated by Ghidra\n\n")
    
    functions = fm.getFunctions(True)
    for func in functions:
        print("Decompiling %s..." % func.getName())
        
        # Decompile the function
        monitor = ConsoleTaskMonitor()
        results = decompiler.decompileFunction(func, 60, monitor)
        
        if results.decompileCompleted():
            decomp = results.getDecompiledFunction()
            if decomp is not None:
                f.write("\n// Function: %s at %s\n" % (func.getName(), func.getEntryPoint()))
                f.write(decomp.getC() + "\n")
                f.write("-" * 80 + "\n")
        else:
            f.write("\n// Failed to decompile: %s\n" % func.getName())
            f.write("-" * 80 + "\n")
    
    f.close()
    decompiler.dispose()
    
    # Export strings
    strings_file = os.path.join(output_dir, "strings_found.txt")
    f = open(strings_file, "w")
    f.write("Strings found in CPR093.exe\n")
    f.write("-" * 50 + "\n\n")
    
    # Get defined strings
    listing = program.getListing()
    datas = listing.getDefinedData(True)
    
    string_count = 0
    for data in datas:
        if data.hasStringValue():
            value = data.getValue()
            if value:
                f.write("%s: %s\n" % (data.getAddress(), value))
                string_count += 1
    
    f.write("\nTotal strings: %d\n" % string_count)
    f.close()
    
    print("Exported %d strings to %s" % (string_count, strings_file))
    print("Export complete!")
