// Decompiled code from CPR093.exe
// Generated by Ghidra


// Function: entry at 1000:0010

/* WARNING: Control flow encountered bad instruction data */

void entry(void)

{
  int iVar1;
  int in_BX;
  int unaff_SI;
  
  iVar1 = Ordinal_100();
  *(int *)(in_BX + unaff_SI) = *(int *)(in_BX + unaff_SI) + iVar1;
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}


--------------------------------------------------------------------------------

// Function: Ordinal_100 at d8c2:0000

/* WARNING: Control flow encountered bad instruction data */

void Ordinal_100(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}


--------------------------------------------------------------------------------
